sonar.projectKey=Puja-Dube02_devops-e2e-pipeline
sonar.organization=puja-dube02

sonar.sources=app/src
sonar.tests=app/test
sonar.exclusions=app/node_modules/**
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
