apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-e2e-app
  namespace: devops-e2e
  labels:
    app: devops-e2e-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-e2e-app
  template:
    metadata:
      labels:
        app: devops-e2e-app
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: app
          image: ghcr.io/puja-dube02/devops-e2e-pipeline:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
